<?php
/*
 * This file was designed to sever the purpose of testing DataShare devel and see if it supports multipart depositing.
 */
    require_once('lib/swordappv2-php-library/packager_atom_multipart.php');
    require_once("lib/swordappv2-php-library/swordappclient.php");

    $testsac = new SWORDAPPClient();

    $testurl = "http://devel.edina.ac.uk:9228/swordv2/servicedocument";

	// The user (if required)
	$testuser = "xi.bai@ed.ac.uk";

	// The password of the user (if required)
	$testpw = "*****************";

	// The on-behalf-of user (if required)
	$testobo = null;

	// The URL of the example deposit collection
	$testdepositurl = "http://devel.edina.ac.uk:9228/handle/123456789/1";

	// The test atom entry to deposit
	$testatomentry = "test-files/atom_multipart/atom";

	// The second test atom entry to deposit
	$testatomentry2 = "test-files/atom_multipart/atom2";

	// The test atom multipart file to deposit
	$testmultipart = "test-files/atom_multipart_package";

	// The second test file to deposit
	$testmultipart2 = "test-files/atom_multipart_package2";

	// The test content zip file to deposit
	$testzipcontentfile = "test-files/atom_multipart_package2.zip";

    // A plain content file
    $testextrafile = "test-files/swordlogo.jpg";

    // The file type of the extra file
    $testextrafiletype = "image/jpg";

	// The content type of the test file
	$testcontenttype = "application/zip";

	// The location of the files (without final directory)
    $test_rootin = '.';

	// The location of the files
    $test_dirin = 'atom_multipart';

    // The location to write the package out to
    $test_rootout = 'test-files';

    // The filename to save the package as
    $test_fileout = 'atom_multipart_package';

    $testpackaging = "http://purl.org/net/sword/package/SimpleZip";


    // Create the test package
	$test_packager = new PackagerAtomMultipart($test_rootin, $test_dirin, $test_rootout, $test_fileout);
	$test_packager->setTitle("site1_camera2_201202051210");
/*     $test_packager->setIdentifier("10.1108/00330330910998057"); */
    $test_packager->addEntryAuthor("Bob Fisher");
    $test_packager->addEntryAuthor("Bas Boom");
    $test_packager->addEntryAuthor("Xi Bai");
    $abstract = "This dataset contains videos and processed results from a set of up to 10
stationary undersea cameras (in Taiwan) that are observing tropical coral reef fish.
The data was acquired over the period Oct 1, 2010 through Sept 30, 2013.
The dataset contains: a) a set of 10 minute videos (approximately 11K clips),
b) a set of files describing the fish detected, tracked and recognised in each
of the videos with one file per video, and c) the full set of detected, tracked and recognised fish from the 3 year project.
The dataset presented here is a < 1T subset of the full 400T dataset
organised as follows:
a) one video clip from each camera from each project day captured at approximately 12:00 noon
(approximately 365*3*10 clips, although not all cameras were working at all times).
This gives some idea of how the data changes over the seasons.
b) one video clip from each camera at every 10 minute interval between
6:00 and 18:00 from a specific day
(approximately 72*10 clips, although not all cameras were working at all times).
This gives some idea of how the data changes over a day.
c) a set of records describing the detected, tracked and recognised fish. These plain-text files are a dump of the associated SQL datasets,
recording the site, camera, time, frame, location in frame, and species of each detected fish,
along with certainty factors and tracking information linking fish frame-to-frame.";
    $test_packager->setSummary($abstract);
    $right = "Any use of the dataset should be acknowledged by:
\"Dataset generated by the EC FP7 funded Fish4Knowledge project: B. J. Boom et al,
Long-term underwater camera surveillance for monitoring and analysis of fish populations,
Proc. Int. Workshop on Visual observation and Analysis of Animal and Insect
Behavior (VAIB), in conjunction with ICPR 2012, Tsukuba, Japan, 2012.\"

There are no other restrictions on the use of the dataset.";
    $test_packager->addMetadata("abstract", $abstract);
    $test_packager->addMetadata("contributor", "Bob Fisher, Bas Boom, Xi Bai");
    $test_packager->addMetadata("publisher", "Institute of Perception, Action &amp; Behaviour (IPAB), School of Informatics, University of Edinburgh");
    $test_packager->addMetadata("type", "Dataset");
    $test_packager->addMetadata("spatial", "Taiwan");
    $test_packager->addMetadata("coverage", "start=2012-02-05T12:10:00Z; end=2012-02-05T12:20:00Z; scheme=W3C-DTF");
    $test_packager->addMetadata("creator", "Fish4Knowledge Project + Taiwan NCHC");
/*     $test_packager->addMetadata("tableOfContents", "datetime:2012-02-05T12:10:00Z,site:NPP,camera:2,id:1"); */
    $test_packager->addMetadata("source", "site:NPP,camera:2,video:1");
    $test_packager->addMetadata("title", "site1_camera2_201202051210");
    $test_packager->addFile("site1_camera2_201202051210.flv");
    $test_packager->addFile("site1_camera2_201202051210.csv");
	$test_packager->create();

	print "About to deposit multipart file (" . $testmultipart . ") to " . $testdepositurl . "\n";
		if (empty($testuser)) {
            print "As: anonymous\n";
        } else {
            print "As: " . $testuser . "\n";
        }
		$testdr = $testsac->depositMultipart($testdepositurl, $testuser, $testpw, null, $testmultipart, $testpackaging, false);
		print "Received HTTP status code: " . $testdr->sac_status . " (" . $testdr->sac_statusmessage . ")\n";

		if (($testdr->sac_status >= 200) || ($testdr->sac_status < 300)) {
            $testdr->toString();
        }


?>
